name: "Aggiungi label non-letto"

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  add-label:
    runs-on: ubuntu-latest

    steps:
      - name: Aggiungi label non-letto
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: non-letto
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
